### ISSUE TITLE
Cleanup and merge with psas/lv3.0-airframe

### ISSUE THREAD

**Issue by Joedang** [psas/mme-capstone#2]
The stuff in this repo should clearly be a part of `psas/lv3.0-airframe`. I'm thinking it would go in something like `/tools/`.

**Comment by 7deeptide** [comment]
Agreed.

**Comment by Joedang** [comment]
The repos have been merged, although the situation with the oven controller is still a bit of a dumpster fire, figuratively speaking. I just put it in an appropriate directory and gave it a README that amounts to "just go get a COTS controller".
